- name: Install required packages
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg

- name: Add Docker GPG key to trusted location
  shell: gpg --batch --yes --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg /tmp/docker.gpg
  become: true

- name: Add Docker repository
  shell: |
    add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  become: true

- name: Install containerd
  apt:
    name: containerd.io
    state: present

- name: Generate containerd configuration
  command: containerd config default
  register: containerd_config
  changed_when: false

- name: Save containerd configuration
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Update containerd to use SystemdCgroup
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^SystemdCgroup = false'
    line: 'SystemdCgroup = true'

- name: Restart and enable containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Add Kubernetes repository
  copy:
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: Download Kubernetes GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /tmp/kubernetes-release.key

- name: Add Kubernetes GPG key to trusted location
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key

- name: Update apt cache after adding Kubernetes repository
  apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Mark Kubernetes packages to hold
  shell: apt-mark hold kubelet kubeadm kubectl
