- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.145.50   k8s-master
      192.168.145.51   k8s-worker1
      192.168.145.52   k8s-worker2
  become: true


- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap.img/s/^/#/' /etc/fstab
  become: true


- name: Verify swap is disabled
  command: free -h
  register: swap_status
  changed_when: false


- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  become: true


- name: Load kernel modules now
  shell: |
    modprobe overlay
    modprobe br_netfilter
  become: true


- name: Set Kubernetes kernel parameters
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  become: true


- name: Apply sysctl parameters
  command: sysctl --system
  become: true


- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true
