---
- name: Install prerequisites for Kubernetes
  hosts: all
  become: true

  tasks:
    - name: Update server
      import_tasks: ../roles/install-prerequisites/tasks/update_server.yml
      
    # - name: Install Kubernetes dependencies
    #   import_tasks: ../roles/install-prerequisites/tasks/install_k8s.yml



